Update gems
Tests were failing because humanize gem suddenly wasn't available in fixtures. e.g:
```
  NoMethodError: undefined method `humanize' for 3:Integer
```
`bundle update` fixed it.